spring:
  datasource:
    url: jdbc:mysql://IP??:???/??????useUnicode=true&useSSL=false&characterEncoding=utf8
    username: ??????
    password: ?????
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
logging:
  level:
    root: ERROR
    org.springframework: ERROR



