spring:
  datasource:
    url: jdbc:mysql://your_ip_address:port/db_name?useUnicode=true&useSSL=false&characterEncoding=utf8 # 数据库地址 端口 数据库名
    username: username # 用户名
    password: password # 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
logging:
  level:
    root: ERROR
    org.springframework: ERROR



